### ISSUE TITLE
Querying sensors in parallel?

### ISSUE THREAD

**Issue by lukeyeager** [gebn/bmc#42]
Is it valid to query multiple sensors in parallel (from multiple worker coroutines)? In the IPMI v2.0 spec, I see a section about "Previous Sequence Number Tracking". I realize that's probably for handling multi-packet responses, but I was hoping I'd be able to send multiple requests in parallel, and that this library would automatically filter the response packets by their sequence number. But it's not working. Sometimes I get errors like `read udp 10.20.170.132:41744->172.22.6.24:623: i/o timeout`, and once I got a big backtrace like this:
```
panic: crypto/cipher: input not full blocks

goroutine 38 [running]:
crypto/cipher.(*cbcEncrypter).CryptBlocks(0xc0002d0b40, 0xc0002b603d, 0x1c, 0x33, 0xc0002b603d, 0x1c, 0x33)
        /usr/lib/go/src/crypto/cipher/cbc.go:59 +0x306
github.com/gebn/bmc/pkg/ipmi.(*AES128CBC).SerializeTo(0xc0002980c0, 0xa8ccd8, 0xc000290190, 0xc000070101, 0x0, 0x0)
        /home/lyeager/go/pkg/mod/github.com/gebn/bmc@v0.0.0-20210524073056-cefdef9b42c0/pkg/ipmi/aes_128_cbc.go:110 +0x27a
github.com/google/gopacket.SerializeLayers(0xa8ccd8, 0xc000290190, 0xc000290101, 0xc00007baf0, 0x5, 0x5, 0x0, 0x0)
        /home/lyeager/go/pkg/mod/github.com/google/gopacket@v1.1.19/writer.go:210 +0xcd
github.com/gebn/bmc.(*V2Session).buildAndSend.func1(0xc00029cae0, 0xc00029cae0)
        /home/lyeager/go/pkg/mod/github.com/gebn/bmc@v0.0.0-20210524073056-cefdef9b42c0/v2session.go:173 +0x1e9
github.com/cenkalti/backoff/v4.RetryNotifyWithTimer(0xc00007bc88, 0xa82dc0, 0xc00029cae0, 0x0, 0xa86470, 0xc00028c2e8, 0x0, 0x0)
        /home/lyeager/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:55 +0x102
github.com/cenkalti/backoff/v4.RetryNotify(...)
        /home/lyeager/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:34
github.com/cenkalti/backoff/v4.Retry(...)
        /home/lyeager/go/pkg/mod/github.com/cenkalti/backoff/v4@v4.1.0/retry.go:28
github.com/gebn/bmc.(*V2Session).buildAndSend(0xc0002bc000, 0xa88480, 0xc00028e1e0, 0xa88870, 0xc0002b4240, 0xc0002d2480, 0x96f980)
        /home/lyeager/go/pkg/mod/github.com/gebn/bmc@v0.0.0-20210524073056-cefdef9b42c0/v2session.go:211 +0x3d9
github.com/gebn/bmc.(*V2Session).SendCommand(0xc0002bc000, 0xa88480, 0xc00028e1e0, 0xa88870, 0xc0002b4240, 0xc0002b0d00, 0x0, 0x0)
        /home/lyeager/go/pkg/mod/github.com/gebn/bmc@v0.0.0-20210524073056-cefdef9b42c0/v2session.go:120 +0x1ee
github.com/gebn/bmc.(*linearSensorReader).Read(0xc0002b4240, 0xa88480, 0xc00028e1e0, 0xa8f780, 0xc0002bc000, 0x0, 0x0, 0x0)
        /home/lyeager/go/pkg/mod/github.com/gebn/bmc@v0.0.0-20210524073056-cefdef9b42c0/sensor_reader.go:80 +0x64
main.poll.func1.2()
        /home/lyeager/code/cluster-monitoring/services/bmc-sensor-exporter/main.go:211 +0x2ee
created by main.poll.func1
        /home/lyeager/code/cluster-monitoring/services/bmc-sensor-exporter/main.go:222 +0x633
exit status 2
```
Is this a limitation of your library, or of the IPMI spec? It looks to me like you simply assume that the next UDP packet is the response to your question, rather than parsing the sequence number and doing a "UDP sliding window" or something like that. https://github.com/gebn/bmc/blob/cefdef9b42c0387b171211452795e573278531af/internal/pkg/transport/transport.go#L108-L140.

**Comment by gebn** [comment]
I thought exactly the same thing when I saw the SDR Repo for the first time - fire up a bunch of goroutines and it'll be done in no time, surely? Unfortunately, that's simply more than the average BMC can handle. I get the impression some of these chips are designed with only enough memory for building literally one packet at a time. When sending parallel requests, I've seen everything from silently dropped messages, to truncated responses, to responses where it appeared the BMC had merged two separate payloads into a single datagram (and the checksum passed - so it was clearly intentional!). Of course the session was a write-off after that and had to be reset.

The main issue though is detection: it's very hard to assess whether a BMC is happy with more than one outstanding request when those that aren't will happily authenticate a mangled response. There's also no guarantee it will remain so after updating the firmware. One of the key goals of this library was to be able to talk to unknown systems, which means not relying on a-priori knowledge (beyond credentials, of course). Given the kind of data that IPMI transmits, I decided correctness was more critical than performance, and it wasn't worth not being able to trust responses. I'm yet to find an IPMI tool that send concurrent requests, I suspect for the same reason.

Regarding the sequence numbers you mentioned, I came to the conclusion these are a decoy. Notably, the spec says to increment the sequence number when retrying a message, so I think it's more for duplicate detection than a mechanism to reconstruct a message stream, despite allusions to sliding windows in other sections. It only resulted in dropped packets and confused BMCs during my testing.

The good news is this is not the end of the world. It's rare for a BMC to take more than a few seconds to dump its SDR Repo, assuming the client is in the same data centre (minimise RTT and retries). You can also retrieve all SDRs once when the session comes up and keep them in memory, which massively speeds up untangling the sensors you care about. Keeping things in lock-step allows further optimisations, like pre-allocating all message structs and other buffers needed for a session when it is created, safe in the knowledge you'll never need two of the same struct at the same time. The [bmc_exporter](https://github.com/gebn/bmc_exporter) does all of the above, and was designed for an environment where there are 10,000+ BMCs being queried every 30s, and overall throughput is more important than the latency of a given operation with a single BMC. You might find [this](https://github.com/gebn/bmc_exporter/blob/master/README.md#deployment) section in the docs useful.
